name: yggdrasil-proxy
services:
  yggdrasil-proxy:
    image: ghcr.io/de-shark/yggdrasil-proxy:latest
    volumes:
      - ./config:/app/config
    ports:
      - "32217:32217"
    restart: unless-stopped
